### ISSUE TITLE
SKIM64 custom install locations

### ISSUE THREAD

**Issue by OppenheimersToy** [Kaldaien/SKIM#2]
SKIM64 isn't able to locate the FFX/X-2 remaster folder, and there's no way to select it manually. Could you include an installation directory selection for non-standard locations?

I noticed my LibraryFolders.vdf on my main Steam game directory tries to point to my SSD steam directory that I use for certain games. Is it possible that SKIM is trying to look at that one instead of the other one? This is currently impossible to test because my SSD is too small to copy over the FFX folder entirely.

**Comment by Kaldaien** [comment]
Yes, and no. Yes, it will run through all of your library folders, so that will include the SSD. But it does not stop looking through library folders until it finds one with your game's manifest.

I have 5 steam libraries across 4 disks on my gaming machine and it works as designed, always finding games no matter which disk I install them to.

If I ever mod a non-Steam game, I will consider adding support for that. Otherwise, this also prevents people from installing the mods on pirated copies of the game. Because the mod will deadlock at start on any pirated copy and I prefer not to get support requests from people who have pirated the game.

**Comment by Kaldaien** [comment]
Could you provide copies of libraryfolders.vdf? Also the manifest for Final Fantasy X/X-2? In the past I ran into at least one system where differences in case were causing parse problems.

**Comment by OppenheimersToy** [comment]
Nevermind, it worked after I restarted and launched the game for the first time. Thanks for responding so quickly!
